
app:
  allow-get-accounts: ${accounts.allow-get-accounts}


spring:
  application:
    name: accounts
  profiles:
    active: production



info:
  app:
    name: "Accounts"
    version: "0.0.1"
    profile: ${spring.profiles.active}
  serverInfo:
    port: ${server.port}



